networks:
  ventinso-network:
    external: true

services:

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - ventinso-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - ventinso-network
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    networks:
      - ventinso-network
    command: listen --forward-to http://host.docker.internal:8083/stripe/webhook
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_DEVICE_NAME: docker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
