CREATE TABLE `orders` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    price DECIMAL(10,2) NOT NULL,
    seller_id BIGINT NOT NULL,
    seller_username VARCHAR(255) NOT NULL,
    delivery_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    buyer_id BIGINT NOT NULL,
    buyer_username VARCHAR(255) NOT NULL,
    arrival_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    item_id BIGINT NOT NULL,
    item_title VARCHAR(255) NOT NULL,
    item_condition VARCHAR(50) NOT NULL,
    thumbnail_url VARCHAR(255) NOT NULL,
    tracking_number VARCHAR(255),
    rating_submitted BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL,
    valid_participants BOOLEAN,
    valid_item BOOLEAN,
    valid_balance BOOLEAN,
    paid_at DATETIME,
    sent_at DATETIME,
    arrived_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
