CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS users;
CREATE DATABASE IF NOT EXISTS inventory;
CREATE DATABASE IF NOT EXISTS orders;
CREATE DATABASE IF NOT EXISTS payments;

GRANT ALL PRIVILEGES ON auth.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON users.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON inventory.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON orders.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON payments.* TO 'root'@'%';

FLUSH PRIVILEGES;
