CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS inventory;
CREATE DATABASE IF NOT EXISTS payments;
CREATE DATABASE IF NOT EXISTS orders;
CREATE DATABASE IF NOT EXISTS users;
CREATE DATABASE IF NOT EXISTS chats;